/* SC-1 operational XLS workflow. The watcher and browser only create previews. */
(function () {
  'use strict';
  var API='/api/v1/imports', SLOTS='/api/v1/terminal-slots', current=null, pending=[], mappingData=null;
  function el(id){return document.getElementById(id)}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]})}
  // Demo mode is decided once, in data-source.js. The fallback reads the raw
  // marker the Pages build injects, so a demo artifact is still recognised even
  // if this file somehow loads first: unknown must never mean "call the API".
  function demo(){return window.OPS_IS_DEMO?window.OPS_IS_DEMO():window.OPS_MODE==='demo'}
  function drawer(title,sub,body,foot){el('dtitle').textContent=title;el('dsub').textContent=sub||'';el('dbody').innerHTML=body;el('dfoot').innerHTML=foot||'<button class="btn" onclick="closeDrawer()">닫기</button>';el('drawerWrap').classList.add('open')}
  function fail(message,detail){drawer('처리하지 못했습니다','근태 데이터는 변경되지 않았습니다.','<div class="alert"><b>'+esc(message)+'</b><br>'+esc(detail||'')+'</div>')}
  function send(url,opt){
    if(demo()&&(/^\/api\/v1\/(imports|terminal-slots)/).test(url)) return Promise.reject(Error('공개 데모에서는 운영 기능을 사용하지 않습니다.'));
    return fetch(url,opt).then(function(r){return r.json().catch(function(){return null}).then(function(x){if(!r.ok)throw Error(x&&x.detail||'요청 실패 ('+r.status+')');return x})});
  }
  function state(p){var active=p.slots.filter(function(s){return s.punchCount>0});var unmapped=active.filter(function(s){return s.status==='unmapped'||s.status==='partial_unmapped'});return{active:active,unmapped:unmapped,blocking:p.findings.filter(function(f){return f.severity==='blocking'})}}
  function employeeOptions(data){return data.employees.map(function(e){var status=e.status==='active'?'재직':('퇴사/비재직'+(e.end_date?' · '+e.end_date:''));return '<option value="'+e.id+'">'+esc(e.name)+' ('+esc(e.employee_code)+' · '+esc(status)+')</option>'}).join('')}
  function refreshPending(){if(demo())return Promise.resolve();return send(API+'/pending').then(function(x){pending=x.pending||[];var b=document.querySelector('header .topbtn.primary');if(b)b.textContent=pending.length?'지문 XLS · 검토 필요 '+pending.length:'지문 XLS 가져오기'}).catch(function(){})}
  window.OPS_IMPORT_REFRESH_PENDING=refreshPending;

  window.OPS_OPEN_IMPORT = function(){if(demo())return drawer('업무용 PC에서만 사용할 수 있습니다','공개 데모','실제 XLS와 운영 데이터는 공개 데모에 연결하지 않습니다.');if(pending.length)return showQueue();window.OPS_OPEN_IMPORT_UPLOAD()};
  window.OPS_OPEN_IMPORT_UPLOAD=function(){if(demo())return window.OPS_OPEN_IMPORT();drawer('지문 XLS 가져오기','SC-1 · 한 달 파일 선택','<div class="box"><input id="importFile" type="file" accept=".xls,.XLS"><p>USB의 XLS를 선택하거나 지정된 폴더에 복사하세요. 먼저 미리보기만 만들며 근태는 바뀌지 않습니다.</p></div><p><button class="btn" onclick="OPS_OPEN_SLOT_MAPPINGS()">SC-1 슬롯 연결 관리</button></p>','<button class="btn" onclick="closeDrawer()">취소</button><button class="btn primary" onclick="OPS_IMPORT_PREVIEW()">미리보기</button>')};
  window.OPS_IMPORT_PREVIEW = function(){if(demo())return window.OPS_OPEN_IMPORT();var f=el('importFile');if(!f||!f.files.length)return window.toast('XLS 파일을 선택하세요.');var form=new FormData();form.append('file',f.files[0]);drawer('파일 확인 중','','<p>원본을 보존하고 미리보기를 만들고 있습니다.</p>','');send(API,{method:'POST',body:form}).then(showPreview).catch(function(e){fail('파일을 읽을 수 없습니다.',e.message)})};
  function showQueue(){var rows=pending.map(function(r){return '<button class="btn" style="width:100%;margin:4px 0;text-align:left" onclick="OPS_IMPORT_REVIEW('+r.importRunId+')"><b>'+esc(r.sourceFilename)+'</b> · <span class="tag amber">'+esc(r.state||'검토 필요')+'</span> · '+esc(r.periodStart)+'~'+esc(r.periodEnd)+' · 새 지문 '+r.newPunches+'건</button>'}).join('');drawer('검토 대기 파일',pending.length+'건 · 자동 반영하지 않습니다.',rows,'<button class="btn" onclick="OPS_OPEN_IMPORT_UPLOAD()">다른 파일 선택</button><button class="btn" onclick="closeDrawer()">닫기</button>')}
  window.OPS_IMPORT_REVIEW=function(id){if(demo())return window.OPS_OPEN_IMPORT();send(API+'/'+id+'/preview').then(showPreview).catch(function(e){fail('미리보기를 열 수 없습니다.',e.message)})};
  function showPreview(p){
    current=p;var s=state(p),mapped=s.active.length-s.unmapped.length,findings=p.findings.filter(function(f){return f.severity!=='info'});
    var slots=s.active.map(function(x){var gap=x.uncoveredDates&&x.uncoveredDates.length?' · 미연결 날짜 '+esc(x.uncoveredDates.join(', ')):'';return '<tr><td><b>'+esc(x.slot)+'</b></td><td>'+(x.status==='unmapped'||x.status==='partial_unmapped'?'<span class="tag amber">직원 연결 필요</span>':esc(x.employee))+gap+'</td><td>'+x.punchCount+'건</td></tr>'}).join('');
    var body='<div class="box"><div class="kv"><div class="k">파일</div><div>'+esc(p.sourceFilename)+'</div><div class="k">근태 월</div><div>'+esc(p.periodStart)+' ~ '+esc(p.periodEnd)+'</div><div class="k">슬롯</div><div>연결 '+mapped+' · 미연결/부분연결 '+s.unmapped.length+'</div><div class="k">새 지문</div><div>'+p.newPunches+'건</div><div class="k">복구 가능</div><div>'+p.reactivatablePunches+'건</div><div class="k">확인 항목</div><div>'+findings.length+'건</div></div></div><h3>SC-1 슬롯</h3><div class="box"><table><tbody>'+slots+'</tbody></table></div>';
    if(s.unmapped.length)body+='<div class="alert"><b>지문이 있는 모든 날짜에 직원 연결이 필요합니다.</b><br>직원을 추측하지 않으며, 빠진 날짜가 있으면 반영할 수 없습니다.</div>';
    if(findings.length)body+='<h3>확인할 내용</h3><div class="box">'+findings.map(function(f){return '<p><b>'+esc(f.slot||f.workDate||'확인')+'</b> '+esc(f.detail)+'</p>'}).join('')+'</div>';
    body+='<p class="sub">미리보기 시각: '+esc((p.previewedAt||'').replace('T',' ').slice(0,19))+'</p><details><summary>기술 정보</summary><p>원본 해시</p><code>'+esc(p.sourceHash)+'</code><p>미리보기 지문</p><code>'+esc(p.previewFingerprint)+'</code></details>';
    var foot='<button class="btn" onclick="closeDrawer()">닫기</button><button class="btn" onclick="OPS_OPEN_SLOT_MAPPINGS()">슬롯 연결 관리</button>'+(s.unmapped.length?'<button class="btn primary" onclick="OPS_MAP_SLOTS()">직원 연결</button>':p.canApply?'<label><input id="importConfirm" type="checkbox"> 내용을 확인했습니다</label><button class="btn primary" onclick="OPS_IMPORT_APPLY()">반영</button>':'');
    drawer('가져오기 미리보기','아직 근태에 반영하지 않았습니다.',body,foot);
  }
  window.OPS_MAP_SLOTS=function(){if(demo())return window.OPS_OPEN_IMPORT();Promise.all([send(SLOTS),Promise.resolve(current)]).then(function(all){var data=all[0],s=state(current),options=employeeOptions(data);var forms=s.unmapped.map(function(x){var gap=x.uncoveredDates&&x.uncoveredDates.length?'<p class="alert">연결 없는 지문 날짜: '+esc(x.uncoveredDates.join(', '))+'</p>':'';return '<div class="box slot-map" data-slot="'+esc(x.slot)+'"><h3>슬롯 '+esc(x.slot)+'</h3>'+gap+'<label>직원<select class="map-employee"><option value="">선택하세요</option>'+options+'</select></label><label>적용 시작일<input class="map-from" type="date" value="'+esc((x.uncoveredDates&&x.uncoveredDates[0])||current.periodStart)+'"></label><label>적용 종료일 (선택)<input class="map-to" type="date"></label></div>'}).join('');drawer('직원 연결','기존 이력은 덮어쓰지 않습니다.',forms,'<button class="btn" onclick="OPS_IMPORT_REVIEW('+current.importRunId+')">취소</button><button class="btn primary" onclick="OPS_SAVE_MAPPINGS()">저장 후 미리보기 갱신</button>')}).catch(function(e){fail('직원 목록을 불러오지 못했습니다.',e.message)})};
  window.OPS_SAVE_MAPPINGS=function(){var forms=[].slice.call(document.querySelectorAll('.slot-map')),items=[];try{forms.forEach(function(f){var employee=Number(f.querySelector('.map-employee').value),from=f.querySelector('.map-from').value,to=f.querySelector('.map-to').value;if(!employee||!from)throw Error('모든 슬롯의 직원과 시작일을 선택하세요.');if(to&&to<from)throw Error('종료일은 시작일보다 빠를 수 없습니다.');items.push({slotCode:f.dataset.slot,employeeId:employee,effectiveFrom:from,effectiveTo:to||null})})}catch(e){return window.toast(e.message)}send(SLOTS+'/batch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mappings:items})}).then(function(){return send(API+'/'+current.importRunId+'/refresh',{method:'POST'})}).then(showPreview).catch(function(e){fail('슬롯 연결을 저장하지 못했습니다.',e.message)})};

  window.OPS_OPEN_SLOT_MAPPINGS=function(){if(demo())return window.OPS_OPEN_IMPORT();send(SLOTS).then(function(data){mappingData=data;var labels={active:'현재 연결',future:'예정',expired:'종료',cancelled:'취소됨'};var rows=data.slots.map(function(slot){var history=data.mappings.filter(function(m){return m.slot_code===slot});return '<div class="box" style="margin-bottom:10px;padding:10px"><h3>슬롯 '+esc(slot)+'</h3>'+(history.length?history.map(function(m){var actions=m.status==='mapped'?'<button class="btn" onclick="OPS_CORRECT_MAPPING('+m.id+')">잘못 연결 정정</button>'+(m.range_status==='active'&&!m.effective_to?' <button class="btn" onclick="OPS_CLOSE_MAPPING('+m.id+')">종료일 지정</button>':''):'';return '<p><span class="tag '+(m.range_status==='active'?'green':'gray')+'">'+labels[m.range_status]+'</span> '+esc(m.effective_from)+' ~ '+esc(m.effective_to||'계속')+' · '+esc(m.employee_name||'미연결')+' '+actions+'</p>'}).join(''):'<p><span class="tag amber">미연결 슬롯</span></p>')+'<button class="btn" onclick="OPS_ADD_SLOT_MAPPING(\''+esc(slot)+'\')">새 기간 연결</button></div>'}).join('');drawer('SC-1 슬롯 연결','현재·예정·종료·취소 이력을 모두 표시합니다.',rows||'<p>발견된 슬롯이 없습니다.</p>','<button class="btn" onclick="OPS_OPEN_IMPORT_UPLOAD()">돌아가기</button>')}).catch(function(e){fail('슬롯 연결을 불러오지 못했습니다.',e.message)})};
  window.OPS_ADD_SLOT_MAPPING=function(slot){var options=employeeOptions(mappingData);drawer('슬롯 '+slot+' 새 연결','과거 연결은 그대로 보존됩니다.','<div class="box slot-map" data-slot="'+esc(slot)+'"><label>직원<select class="map-employee"><option value="">선택하세요</option>'+options+'</select></label><label>적용 시작일<input class="map-from" type="date"></label><label>적용 종료일 (선택)<input class="map-to" type="date"></label></div>','<button class="btn" onclick="OPS_OPEN_SLOT_MAPPINGS()">취소</button><button class="btn primary" onclick="OPS_SAVE_STANDALONE_MAPPING()">저장</button>')};
  window.OPS_SAVE_STANDALONE_MAPPING=function(){var f=document.querySelector('.slot-map'),employee=Number(f.querySelector('.map-employee').value),from=f.querySelector('.map-from').value,to=f.querySelector('.map-to').value;if(!employee||!from)return window.toast('직원과 시작일을 선택하세요.');if(to&&to<from)return window.toast('종료일은 시작일보다 빠를 수 없습니다.');send(SLOTS,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({slotCode:f.dataset.slot,employeeId:employee,effectiveFrom:from,effectiveTo:to||null})}).then(window.OPS_OPEN_SLOT_MAPPINGS).catch(function(e){fail('연결을 저장하지 못했습니다.',e.message)})};
  window.OPS_CORRECT_MAPPING=function(id){var m=mappingData.mappings.filter(function(x){return x.id===id})[0],options=employeeOptions(mappingData);drawer('잘못 연결 정정','이미 반영된 지문이 있으면 먼저 가져오기를 되돌려야 합니다.','<div class="box"><p>슬롯 '+esc(m.slot_code)+' · '+esc(m.effective_from)+' ~ '+esc(m.effective_to||'계속')+'</p><label>올바른 직원<select id="correctEmployee"><option value="">선택하세요</option>'+options+'</select></label><label>정정 이유<input id="correctReason" type="text" maxlength="500"></label></div>','<button class="btn" onclick="OPS_OPEN_SLOT_MAPPINGS()">취소</button><button class="btn primary" onclick="OPS_SAVE_MAPPING_CORRECTION('+id+')">정정</button>')};
  window.OPS_SAVE_MAPPING_CORRECTION=function(id){var employee=Number(el('correctEmployee').value),reason=el('correctReason').value.trim();if(!employee||reason.length<2)return window.toast('올바른 직원과 정정 이유를 입력하세요.');send(SLOTS+'/'+id+'/correct',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({employeeId:employee,reason:reason})}).then(function(){if(current)return send(API+'/'+current.importRunId+'/refresh',{method:'POST'}).then(showPreview);return window.OPS_OPEN_SLOT_MAPPINGS()}).catch(function(e){fail('연결을 정정하지 못했습니다.',e.message)})};
  window.OPS_CLOSE_MAPPING=function(id){var end=prompt('이 연결의 마지막 적용일을 YYYY-MM-DD로 입력하세요.');if(!end)return;send(SLOTS+'/'+id+'/close',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({effectiveTo:end})}).then(window.OPS_OPEN_SLOT_MAPPINGS).catch(function(e){fail('종료일을 저장하지 못했습니다.',e.message)})};

  window.OPS_IMPORT_APPLY = function(){if(demo())return window.OPS_OPEN_IMPORT();if(!current||!el('importConfirm')||!el('importConfirm').checked)return window.toast('확인란을 선택하세요.');send(API+'/'+current.importRunId+'/apply',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmationToken:current.confirmationToken})}).then(function(r){refreshPending();drawer('반영 완료',current.sourceFilename,'<div class="box">새 지문 '+r.inserted+'건 · 복구 '+r.reactivated+'건 · 근태 '+r.attendanceRows+'일을 갱신했습니다.</div>','<button class="btn" onclick="OPS_IMPORT_ROLLBACK('+r.importRunId+')">되돌리기</button><button class="btn primary" onclick="closeDrawer();OPS_RELOAD()">화면 갱신</button>')}).catch(function(e){fail('반영하지 못했습니다.',e.message)})};
  window.OPS_IMPORT_ROLLBACK = function(id){if(demo())return window.OPS_OPEN_IMPORT();drawer('가져오기 되돌리기','원본 지문은 삭제하지 않습니다.','<div class="box"><label>되돌리는 이유<input id="rollbackReason" type="text" maxlength="500" placeholder="예: 직원 연결을 잘못 선택함"></label></div>','<button class="btn" onclick="closeDrawer()">취소</button><button class="btn primary" onclick="OPS_CONFIRM_ROLLBACK('+id+')">되돌리기</button>')};
  window.OPS_CONFIRM_ROLLBACK=function(id){var reason=(el('rollbackReason').value||'').trim();if(reason.length<2)return window.toast('되돌리는 이유를 입력하세요.');send(API+'/'+id+'/rollback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason:reason})}).then(function(r){refreshPending();if(window.OPS_RELOAD)window.OPS_RELOAD();var conflicts=r.conflicts||[],body='<div class="box">지문 '+r.punchesMarkedRolledBack+'건을 되돌렸고 근태 '+r.attendanceRecomputed+'일을 다시 계산했습니다. 원본 기록은 삭제하지 않았습니다.</div>';if(conflicts.length)body+='<div class="alert"><b>완전히 되돌리지 못한 근태 '+conflicts.length+'건</b><br>확정하거나 수동 수정한 근태는 변경하지 않았습니다.</div>'+conflicts.map(function(c){return '<div class="box"><b>'+esc(c.workDate||'날짜 확인 필요')+'</b> · '+esc(c.detail||'수동 변경된 근태')+'</div>'}).join('');drawer(conflicts.length?'일부 항목 제외 후 되돌리기 완료':'되돌리기 완료','',body)}).catch(function(e){fail('되돌리지 못했습니다.',e.message)})};
  window.OPS_OPEN_IMPORT_HISTORY = function(){if(demo())return drawer('업무용 PC에서만 사용할 수 있습니다','공개 데모','원본기록과 가져오기 이력은 공개 데모에 연결하지 않습니다.');send(API).then(function(runs){drawer('원본기록 · 가져오기 이력','',runs.map(function(r){return '<div class="box"><b>'+esc(r.sourceFilename)+'</b> · '+esc(r.status)+(r.status==='applied'?'<button class="btn" onclick="OPS_IMPORT_ROLLBACK('+r.id+')">되돌리기</button>':'')+'</div>'}).join(''))}).catch(function(e){fail('이력을 불러오지 못했습니다.',e.message)})};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',refreshPending);else refreshPending();
})();
