/* Phase 4 deterministic operational leave/replacement UI. Demo exits before fetch. */
(function(){'use strict';
var LEAVE='/api/v1/leave-operations',REPL='/api/v1/replacement-operations',leaveData=null,replData=null,now=new Date(),selectedMonth=now.getFullYear()+'-'+String(now.getMonth()+1).padStart(2,'0');
function demo(){return window.OPS_MODE_ACTIVE==='demo'}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]})}
function send(url,opt){if(demo())return Promise.reject(Error('공개 데모에서는 운영 기능을 사용하지 않습니다.'));return fetch(url,opt).then(function(r){return r.json().catch(function(){return null}).then(function(x){if(!r.ok)throw Error(x&&x.detail||'요청 실패 ('+r.status+')');return x})})}
function drawer(title,sub,body,foot){dtitle.textContent=title;dsub.textContent=sub||'';dbody.innerHTML=body;dfoot.innerHTML=foot||'<button class="btn" onclick="closeDrawer()">닫기</button>';drawerWrap.classList.add('open')}
function error(e){drawer('처리하지 못했습니다','기존 데이터는 변경되지 않았습니다.','<div class="alert">'+esc(e.message)+'</div>')}
function options(data,activeOnly){return data.employees.filter(function(e){return !activeOnly||e.status==='active'}).map(function(e){return '<option value="'+e.id+'">'+esc(e.name)+' ('+esc(e.employee_code)+' · '+esc(e.status)+(e.end_date?' · '+esc(e.end_date):'')+')</option>'}).join('')}
function iso(v){return v||null}
function reloadAll(){var main=window.OPS_RELOAD?window.OPS_RELOAD():Promise.resolve(),query='?month='+selectedMonth;return Promise.all([main,send(LEAVE+query),send(REPL+query)]).then(function(all){leaveData=all[1];replData=all[2];var title=document.getElementById('leaveMonth'),p=selectedMonth.split('-');if(title)title.textContent=p[0]+'년 '+Number(p[1])+'월';paintLeave();paintReplacements()}).catch(error)}
function moveMonth(delta){var p=selectedMonth.split('-'),d=new Date(Number(p[0]),Number(p[1])-1+delta,1);selectedMonth=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');reloadAll()}
function paintLeave(){var body=document.getElementById('leaveTable'),summary=document.getElementById('leaveSummary');if(!body||!leaveData)return;var labels={annual_leave:'연차',half_day:'반차',sick_leave:'병가',other_authorized_leave:'기타 승인휴가'},status={requested:'승인 대기',approved:'승인',cancelled:'취소',rejected:'반려',draft:'작성 중'},findingLabels={sick_leave_evidence_mismatch:'기간 불일치',leave_attendance_conflict:'휴가·근태 충돌',partial_leave_review:'반차 확인'};var leaves=leaveData.leaves,balanceNames={};leaveData.employees.forEach(function(e){balanceNames[e.id]=e.name});summary.innerHTML='<div class="sum"><b>'+leaves.length+'</b><span>전체</span></div><div class="sum"><b>'+leaves.filter(function(x){return x.status==='requested'}).length+'</b><span>승인 대기</span></div><div class="sum"><b>'+leaves.filter(function(x){return (x.findings||[]).length||x.finding}).length+'</b><span>확인 필요</span></div>'+(leaveData.balances||[]).filter(function(b){return b.entitlement>0}).map(function(b){return '<div class="sum"><b>'+b.remaining+'일</b><span>'+esc(balanceNames[b.employeeId])+' '+leaveData.balanceYear+' 잔여</span></div>'}).join('');body.innerHTML=leaves.map(function(x){var findings=x.findings||[x.finding].filter(Boolean),ev=x.evidenceReceived?(esc(x.evidenceStartDate||'날짜 없음')+' ~ '+esc(x.evidenceEndDate||'날짜 없음')):'미수령',editable=x.status==='requested'||x.status==='approved',badges=findings.map(function(f){return '<span class="tag red">'+esc(findingLabels[f]||f)+'</span> '}).join('');return '<tr class="'+(findings.length?'issueRow':'')+'"><td><b>'+esc(x.employee)+'</b></td><td>'+labels[x.leaveType]+' '+(x.portion==='am'?'오전':x.portion==='pm'?'오후':'')+'</td><td>신청 '+esc(x.startDate)+' ~ '+esc(x.endDate)+(x.leaveType==='sick_leave'?'<div class="sub">증빙 '+ev+'</div>':'')+'</td><td>'+x.calculatedDays+'일</td><td>'+(badges||ev)+'</td><td><span class="tag '+(x.status==='approved'?'green':'gray')+'">'+status[x.status]+'</span><div>'+(editable?'<button class="btn" onclick="OPS_EDIT_LEAVE('+x.id+')">수정</button> ':'')+(x.status==='requested'?'<button class="btn primary" onclick="OPS_APPROVE_LEAVE('+x.id+')">승인</button> ':'')+(editable?'<button class="btn" onclick="OPS_CANCEL_LEAVE('+x.id+')">취소</button>':'')+'</div></td></tr>'}).join('')||'<tr><td colspan="6">휴가 기록이 없습니다.</td></tr>'}
function paintReplacements(){var page=document.getElementById('page-leave'),host=document.getElementById('replacementOps');if(!page||!replData)return;if(!host){host=document.createElement('section');host.id='replacementOps';host.className='panel';host.style.marginTop='14px';page.appendChild(host)}var labels={planned:'계획',confirmed:'확정',completed:'완료',cancelled:'취소'};host.innerHTML='<div class="panelhead"><h1>대체근무</h1><div class="right"><button class="btn primary" onclick="OPS_NEW_REPLACEMENT()">+ 대체 배정</button></div></div><table><thead><tr><th>기간</th><th>결원</th><th>대체</th><th>구역</th><th>상태</th><th>체크</th></tr></thead><tbody>'+replData.assignments.map(function(x){var c=x.checklist,active=x.status==='planned'||x.status==='confirmed';return '<tr><td>'+esc(x.startDate)+' ~ '+esc(x.endDate)+'</td><td>'+esc(x.absent||'미지정')+'</td><td>'+esc(x.replacement)+'</td><td>'+esc(x.zone||'')+'</td><td><span class="tag purple">'+labels[x.status]+'</span><div>'+(active?'<button class="btn" onclick="OPS_EDIT_REPLACEMENT('+x.id+')">변경</button> ':'')+(x.status==='planned'?'<button class="btn" onclick="OPS_REPL_STATUS('+x.id+',\'confirmed\')">확정</button>':'')+(x.status==='confirmed'?'<button class="btn" onclick="OPS_REPL_STATUS('+x.id+',\'completed\')">완료</button>':'')+(active?'<button class="btn" onclick="OPS_REPL_STATUS('+x.id+',\'cancelled\')">취소</button>':'')+'</div></td><td><label><input type="checkbox" '+(c.keyReceived?'checked':'')+' onchange="OPS_CHECK('+x.id+',\'keyReceived\',this.checked)">열쇠</label> <label><input type="checkbox" '+(c.uniformReady?'checked':'')+' onchange="OPS_CHECK('+x.id+',\'uniformReady\',this.checked)">복장</label> <label><input type="checkbox" '+(c.orientationDone?'checked':'')+' onchange="OPS_CHECK('+x.id+',\'orientationDone\',this.checked)">안내</label></td></tr>'}).join('')+'</tbody></table>'}
function leaveForm(x){x=x||{};var sick=x.leaveType==='sick_leave';return '<div class="box" id="leaveForm"><label>직원<select id="lvEmployee"><option value="">선택</option>'+options(leaveData,false)+'</select></label><label>종류<select id="lvType"><option value="annual_leave">연차</option><option value="half_day">반차</option><option value="sick_leave">병가</option><option value="other_authorized_leave">기타 승인휴가</option></select></label><label>시간<select id="lvPortion"><option value="full">종일</option><option value="am">오전 반차</option><option value="pm">오후 반차</option></select></label><label>시작일<input id="lvStart" type="date" value="'+esc(x.startDate||'')+'"></label><label>종료일<input id="lvEnd" type="date" value="'+esc(x.endDate||'')+'"></label><label>사유/메모<input id="lvReason" value="'+esc(x.reason||'')+'"></label><hr><label><input id="lvEvidence" type="checkbox" '+(x.evidenceReceived?'checked':'')+'> 병가 증빙 수령</label><label>증빙 시작일<input id="lvEvStart" type="date" value="'+esc(x.evidenceStartDate||'')+'"></label><label>증빙 종료일<input id="lvEvEnd" type="date" value="'+esc(x.evidenceEndDate||'')+'"></label><label>증빙 메모<input id="lvEvNote" value="'+esc(x.evidenceNote||'')+'"></label></div>'}
function leavePayload(){return{employeeId:Number(lvEmployee.value),leaveType:lvType.value,portion:lvPortion.value,startDate:lvStart.value,endDate:lvEnd.value,reason:lvReason.value||null,evidenceReceived:lvEvidence.checked,evidenceStartDate:iso(lvEvStart.value),evidenceEndDate:iso(lvEvEnd.value),evidenceNote:lvEvNote.value||null}}
window.OPS_NEW_LEAVE=function(){if(demo())return toast('공개 데모에서는 저장하지 않습니다.');drawer('휴가 등록','근무일 기준으로 일수를 계산합니다.',leaveForm(),'<button class="btn" onclick="closeDrawer()">취소</button><button class="btn primary" onclick="OPS_SAVE_LEAVE()">등록</button>')};
window.OPS_SAVE_LEAVE=function(id){var p=leavePayload();send(id?LEAVE+'/'+id:LEAVE,{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)}).then(function(){closeDrawer();return reloadAll()}).catch(error)};
window.OPS_EDIT_LEAVE=function(id){var x=leaveData.leaves.filter(function(v){return v.id===id})[0];drawer('휴가 수정','기존 행을 유지하고 변경 이력을 기록합니다.',leaveForm(x),'<button class="btn" onclick="closeDrawer()">취소</button><button class="btn primary" onclick="OPS_SAVE_LEAVE('+id+')">수정 저장</button>');lvEmployee.value=x.employeeId;lvType.value=x.leaveType;lvPortion.value=x.portion};
window.OPS_APPROVE_LEAVE=function(id){send(LEAVE+'/'+id+'/approve',{method:'POST'}).then(reloadAll).catch(error)};
window.OPS_CANCEL_LEAVE=function(id){drawer('휴가 취소','','<label>취소 이유<input id="lvCancelReason"></label>','<button class="btn" onclick="closeDrawer()">닫기</button><button class="btn primary" onclick="OPS_CONFIRM_CANCEL_LEAVE('+id+')">취소 처리</button>')};
window.OPS_CONFIRM_CANCEL_LEAVE=function(id){send(LEAVE+'/'+id+'/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason:lvCancelReason.value})}).then(function(){closeDrawer();return reloadAll()}).catch(error)};
function replacementForm(x){x=x||{};return '<div class="box"><label>결원 직원<select id="rpAbsent"><option value="">선택</option>'+options(replData,false)+'</select></label><label>대체 직원<select id="rpWorker"><option value="">선택</option>'+options(replData,true)+'</select></label><label>시작일<input id="rpStart" type="date" value="'+esc(x.startDate||'')+'"></label><label>종료일<input id="rpEnd" type="date" value="'+esc(x.endDate||'')+'"></label><label>구역<input id="rpZone" value="'+esc(x.zone||'')+'"></label><label>메모<input id="rpNote" value="'+esc(x.note||'')+'"></label></div>'}
window.OPS_NEW_REPLACEMENT=function(){drawer('대체근무 배정','관리자가 직접 대체근무자를 선택합니다.',replacementForm(),'<button class="btn" onclick="closeDrawer()">취소</button><button class="btn primary" onclick="OPS_SAVE_REPLACEMENT()">배정</button>')};
window.OPS_EDIT_REPLACEMENT=function(id){var x=replData.assignments.filter(function(v){return v.id===id})[0];drawer('대체근무 변경','변경 이력은 감사 기록에 남습니다.',replacementForm(x),'<button class="btn" onclick="closeDrawer()">취소</button><button class="btn primary" onclick="OPS_SAVE_REPLACEMENT('+id+')">변경 저장</button>');rpAbsent.value=x.absentEmployeeId||'';rpWorker.value=x.replacementEmployeeId};
window.OPS_SAVE_REPLACEMENT=function(id){var body={absentEmployeeId:Number(rpAbsent.value)||null,replacementEmployeeId:Number(rpWorker.value),startDate:rpStart.value,endDate:rpEnd.value,zone:rpZone.value||null,note:rpNote.value||null};if(!id)body.status='planned';send(id?REPL+'/'+id:REPL,{method:id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}).then(function(){closeDrawer();return reloadAll()}).catch(error)};
window.OPS_REPL_STATUS=function(id,status){send(REPL+'/'+id+'/status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:status})}).then(reloadAll).catch(error)};
window.OPS_CHECK=function(id,key,value){var body={};body[key]=value;send(REPL+'/'+id+'/checklist',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}).then(reloadAll).catch(error)};
function init(){if(demo())return;var toolbar=document.querySelector('#page-leave .toolbar'),button=document.querySelector('#page-leave .toolbar .primary'),arrows=toolbar?toolbar.querySelectorAll('.datebox button'):[];if(button){button.onclick=window.OPS_NEW_LEAVE;button.textContent='+ 휴가 등록'}if(arrows.length===2){arrows[0].onclick=function(){moveMonth(-1)};arrows[1].onclick=function(){moveMonth(1)}}reloadAll()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
